import{a as q,S as R,i as n}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const E="https://pixabay.com/api/",M="54828385-3257320bcaeec570fd5a64756",$=15;async function h(r,o){return(await q.get(E,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:$}})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".load-more"),B=new R(".gallery a",{captionsData:"alt",captionDelay:250});function m(r){const o=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:a,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${t}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${v}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function A(){f.innerHTML=""}function y(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function L(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}const d=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",c=1,u=0;const P=15;d.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){n.warning({message:"Please enter a search query!",position:"topRight"});return}l=o,c=1,A(),w(),y();try{const s=await h(l,c);if(u=s.totalHits,s.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(m(s.hits),Math.ceil(u/P)===1){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}L()}catch{n.error({message:"Something went wrong.",position:"topRight"})}finally{b()}d.reset()});O.addEventListener("click",async()=>{c+=1,w(),y();try{const r=await h(l,c);if(r.hits.length===0){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}m(r.hits);const o=Math.ceil(u/P);c>=o?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L();const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch{n.error({message:"Something went wrong.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
