import{a as q,S as v,i}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const E="https://pixabay.com/api/",R="54828385-3257320bcaeec570fd5a64756",$=15;async function f(n,o){return(await q.get(E,{params:{key:R,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:$}})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const o=n.map(({webformatURL:r,largeImageURL:c,tags:e,likes:t,views:s,comments:P,downloads:S})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${r}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${t}</p>
          <p><b>Views</b> ${s}</p>
          <p><b>Comments</b> ${P}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){m.innerHTML=""}function y(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function A(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}const u=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",a=1,d=0;const w=15;u.addEventListener("submit",async n=>{n.preventDefault();const o=n.target.elements["search-text"].value.trim();if(!o){i.warning({message:"Please enter a search query!",position:"topRight"});return}l=o,a=1,M(),b(),y();try{const r=await f(l,a);if(d=r.totalHits,r.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(r.hits),d>w&&A()}catch{i.error({message:"Something went wrong.",position:"topRight"})}finally{L()}u.reset()});O.addEventListener("click",async()=>{a+=1,y();try{const n=await f(l,a);g(n.hits);const o=Math.ceil(d/w);a>=o&&(b(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{i.error({message:"Something went wrong.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
